default: &default
  adapter: postgresql
  host: sephoradb.cgp62gfwcyhi.ap-south-1.rds.amazonaws.com

development:
  <<: *default
  database: sephoradb
  username: root
  password: password


test: &test
  <<: *default
  database: sephoradb
  username: root
  min_messages: warning
  password: password

production:
  <<: *default
  database: sephoradb
  username: root
  password: password
